### ISSUE TITLE
spring-cloud一些jar版本已经变化

### ISSUE THREAD

**Issue by miguanxiong** [417511458/jbone#22]
jbone-cas-server中依赖的这些RC版本的jar目前已经变成稳定版本的了。RC是下不到了。
spring-cloud-commons:jar:2.1.0.RC2 
spring-cloud-context:jar:2.1.0.RC2 
spring-cloud-config-client:jar:2.1.0.RC3 
对应改为：
spring-cloud-commons:jar:2.1.0.RELEASE
spring-cloud-context:jar:2.1.0.RELEASE
spring-cloud-config-client:jar:2.1.0.RELEASE

**Comment by 417511458** [comment]
好的，感谢反馈。我确认下。

**Comment by 417511458** [comment]
已经升级，感谢反馈。
